import type { LucideIcon } from "lucide-react";
import {
  Anchor,
  BookHeart,
  BookOpen,
  Brain,
  Candy,
  Castle,
  Cat,
  CloudRain,
  Coffee,
  Compass,
  Drama,
  Eye,
  Feather,
  Film,
  Flame,
  Ghost,
  Glasses,
  GraduationCap,
  Headphones,
  Heart,
  Leaf,
  Library,
  Lightbulb,
  Map,
  Moon,
  Mountain,
  Music,
  Palette,
  Puzzle,
  Rainbow,
  Flower2,
  Search,
  Ship,
  Skull,
  Snowflake,
  Sparkles,
  Star,
  Sun,
  Sword,
  TreePine,
  Umbrella,
  Wand2,
  Wine,
  Zap,
} from "lucide-react";

export const MOOD_ICON_NAMES = [
  "book-open",
  "graduation-cap",
  "coffee",
  "castle",
  "heart",
  "cloud-rain",
  "sparkles",
  "search",
  "moon",
  "sun",
  "flame",
  "snowflake",
  "tree-pine",
  "feather",
  "ghost",
  "skull",
  "drama",
  "music",
  "wine",
  "leaf",
  "mountain",
  "ship",
  "sword",
  "wand-2",
  "cat",
  "star",
  "zap",
  "eye",
  "book-heart",
  "library",
  "glasses",
  "umbrella",
  "rainbow",
  "flower-2",
  "candy",
  "compass",
  "map",
  "anchor",
  "brain",
  "lightbulb",
  "palette",
  "film",
  "headphones",
  "puzzle",
] as const;

export type MoodIconName = (typeof MOOD_ICON_NAMES)[number];

const moodIconMap: Record<MoodIconName, LucideIcon> = {
  "book-open": BookOpen,
  "graduation-cap": GraduationCap,
  coffee: Coffee,
  castle: Castle,
  heart: Heart,
  "cloud-rain": CloudRain,
  sparkles: Sparkles,
  search: Search,
  moon: Moon,
  sun: Sun,
  flame: Flame,
  snowflake: Snowflake,
  "tree-pine": TreePine,
  feather: Feather,
  ghost: Ghost,
  skull: Skull,
  drama: Drama,
  music: Music,
  wine: Wine,
  leaf: Leaf,
  mountain: Mountain,
  ship: Ship,
  sword: Sword,
  "wand-2": Wand2,
  cat: Cat,
  star: Star,
  zap: Zap,
  eye: Eye,
  "book-heart": BookHeart,
  library: Library,
  glasses: Glasses,
  umbrella: Umbrella,
  rainbow: Rainbow,
  "flower-2": Flower2,
  candy: Candy,
  compass: Compass,
  map: Map,
  anchor: Anchor,
  brain: Brain,
  lightbulb: Lightbulb,
  palette: Palette,
  film: Film,
  headphones: Headphones,
  puzzle: Puzzle,
};

const moodIconSet = new Set<string>(MOOD_ICON_NAMES);

export function isValidMoodIcon(icon: string): icon is MoodIconName {
  return moodIconSet.has(icon);
}

export function getMoodIcon(icon: string): LucideIcon {
  if (isValidMoodIcon(icon)) return moodIconMap[icon];
  return BookOpen;
}

export function formatMoodIconLabel(icon: MoodIconName): string {
  return icon
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}
